baseURL = "https://hangsau.github.io/cortex/"
languageCode = "zh-tw"
title = "Cortex"
defaultContentLanguage = "zh-tw"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github-dark"
  lineNos = false

[params]
  description = "個人知識庫"
  author = ""
  cscsFlashcardsCSV = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS_qbjIe5MXYFLj7THraEwn2rZvlrtLSHUgU-ufCZkvbVSEkYq_0rDbXGfttWPoGrPErOngkg_6px41/pub?output=csv"

[menu]
  [[menu.main]]
    name = "書庫"
    url = "/library/"
    weight = 1
  [[menu.main]]
    name = "筆記"
    url = "/notebook/"
    weight = 2
